language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "FXqUn/NJ/bOx3uLjdHadmNEfbQB9nnG3h9dUyOZ3QourGSRwyGz/d8qWkkDQd+azmXElPJZeskNPPTIUQlTNLcBdgxlbL4DMtsGhkdVQcU65IkTnhYgJ8KAz6byD0hNSYQnhf9wDGw6AhDidl48MtHgJnei8BZGD7R68h61BhRbRFciSFwbrPE0vnR+n4fTaViXp4zM85PzZw30kl8jJeDrnA4CmfJxJAmzVVnqOqM54nLgTswlKeXrBM4Rp3v1IEk6Yd1jCMew8CuE6QvrVFJyugKw/T8cgFoCpHro5k92bhP0roVDcGIoapKYLib88a3MbxXVSMJBVKM9RblyYP5ly6/dSgCl5YVIhMuwH8o4kpd296qV7FiRDpVWhkC+yKPlh37rmOj4nCIOpETlv1l/Tg4Ru2rkzJ+agv0iLThkEIaadmQMvv4UP+lPYpO2grY3tNRVWiny3I6xqdHKUBXE3FyaMFIbbmur/T5jVd0oJrYFw+G+mXVhKL5vSEFPUtjYiHOJz2OqEKqnNBEQ1zpb1sUREkEJMDldK9yIbFIlCtXGOo8mic9wPzkYUyXEyLdgTpwM2atAJ40GKF+lrLg9bB5OdgXhhb2co46TxycjACUbMBiasxPaKhpcWGCE39LQXWRFxpWPRSeCvcST47YkDK83a1+pecrNuw+fxn2U="
